-- 004_saved_loads_and_calculations.sql
-- Safe to rerun.
-- Purpose: saved loads, post-trip actuals, lane templates, and calculation snapshots.

create table if not exists public.saved_loads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  status text not null default 'saved',
  pickup_zip text not null,
  delivery_zip text not null,
  loaded_miles numeric(12,2) not null default 0,
  deadhead_miles numeric(12,2) not null default 0,
  rate_per_mile numeric(12,3) not null default 0,
  gross_revenue numeric(12,2) not null default 0,
  total_miles numeric(12,2) not null default 0,
  fuel_cost numeric(12,2) not null default 0,
  operational_cost numeric(12,2) not null default 0,
  estimated_net numeric(12,2) not null default 0,
  true_rpm numeric(12,3) not null default 0,
  profitability_score integer not null default 0,
  profitability_band text not null default 'moderate',
  warnings jsonb not null default '[]'::jsonb,
  input_snapshot jsonb not null default '{}'::jsonb,
  result_snapshot jsonb not null default '{}'::jsonb,
  actuals_snapshot jsonb not null default '{}'::jsonb,
  pay_structure_snapshot jsonb not null default '{}'::jsonb,
  calculation_version text not null default 'loadiq-v1.1-profile-overhead',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.saved_loads
  add column if not exists status text not null default 'saved',
  add column if not exists loadiq_load_number text,
  add column if not exists driver_load_number text,
  add column if not exists load_name text,
  add column if not exists load_outcome text not null default 'unknown',
  add column if not exists load_run_status text default 'planned',
  add column if not exists was_run_status text,
  add column if not exists pickup_zip text,
  add column if not exists pickup_city text,
  add column if not exists pickup_state text,
  add column if not exists delivery_zip text,
  add column if not exists delivery_city text,
  add column if not exists delivery_state text,
  add column if not exists loaded_miles numeric(12,2) not null default 0,
  add column if not exists deadhead_miles numeric(12,2) not null default 0,
  add column if not exists total_miles numeric(12,2) not null default 0,
  add column if not exists route_loaded_miles numeric(12,2) default 0,
  add column if not exists actual_loaded_miles numeric(12,2) default 0,
  add column if not exists route_deadhead_miles numeric(12,2) default 0,
  add column if not exists actual_deadhead_miles numeric(12,2) default 0,
  add column if not exists rate_per_mile numeric(12,3) not null default 0,
  add column if not exists load_pay numeric(12,2) default 0,
  add column if not exists fuel_surcharge numeric(12,2) default 0,
  add column if not exists accessorials numeric(12,2) default 0,
  add column if not exists tolls numeric(12,2) default 0,
  add column if not exists lumper_fees numeric(12,2) default 0,
  add column if not exists detention numeric(12,2) default 0,
  add column if not exists layover numeric(12,2) default 0,
  add column if not exists post_trip_costs numeric(12,2) default 0,
  add column if not exists mpg numeric(8,2) default 6.50,
  add column if not exists fuel_price numeric(10,3) default 0,
  add column if not exists estimated_fuel_cost numeric(12,2) default 0,
  add column if not exists fuel_cost numeric(12,2) not null default 0,
  add column if not exists fuel_estimate_source text,
  add column if not exists estimated_fuel_price numeric(10,3),
  add column if not exists actual_fuel_price numeric(10,3),
  add column if not exists fuel_override boolean not null default false,
  add column if not exists eia_period text,
  add column if not exists fuel_fetched_at timestamptz,
  add column if not exists dispatch_days numeric(8,2) default 1,
  add column if not exists deadhead_days numeric(8,2) default 0,
  add column if not exists daily_overhead numeric(12,2) default 0,
  add column if not exists overhead_applied numeric(12,2) default 0,
  add column if not exists dispatch_fee numeric(12,2) default 0,
  add column if not exists factoring_fee numeric(12,2) default 0,
  add column if not exists lease_deduction numeric(12,2) default 0,
  add column if not exists maintenance_reserve numeric(12,2) default 0,
  add column if not exists gross_revenue numeric(12,2) not null default 0,
  add column if not exists payable_revenue numeric(12,2) default 0,
  add column if not exists net_revenue numeric(12,2) default 0,
  add column if not exists total_expenses numeric(12,2) default 0,
  add column if not exists operational_cost numeric(12,2) not null default 0,
  add column if not exists total_trip_cost numeric(12,2) default 0,
  add column if not exists net_profit numeric(12,2) default 0,
  add column if not exists estimated_net numeric(12,2) not null default 0,
  add column if not exists actual_net numeric(12,2),
  add column if not exists profit_per_mile numeric(12,3) default 0,
  add column if not exists profit_per_loaded_mile numeric(12,3) default 0,
  add column if not exists profit_per_total_mile numeric(12,3) default 0,
  add column if not exists profit_per_day numeric(12,2) default 0,
  add column if not exists profit_per_hour numeric(12,2) default 0,
  add column if not exists true_rpm numeric(12,3) not null default 0,
  add column if not exists break_even_rpm numeric(12,3) default 0,
  add column if not exists target_rpm numeric(12,3) default 0,
  add column if not exists income_target_comparison numeric(12,2) default 0,
  add column if not exists profitability_score integer not null default 0,
  add column if not exists profitability_rating text,
  add column if not exists profitability_band text not null default 'moderate',
  add column if not exists warnings jsonb not null default '[]'::jsonb,
  add column if not exists used_profile_values jsonb not null default '{}'::jsonb,
  add column if not exists used_temporary_overrides jsonb not null default '{}'::jsonb,
  add column if not exists profile_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists calculation_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists input_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists result_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists actuals_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists pay_structure_snapshot jsonb not null default '{}'::jsonb,
  add column if not exists accessorial_items_snapshot jsonb not null default '[]'::jsonb,
  add column if not exists calculation_version text not null default 'loadiq-v1.1-profile-overhead',
  add column if not exists calculated_at timestamptz default now(),
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create table if not exists public.load_estimates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  saved_load_id uuid references public.saved_loads(id) on delete cascade,
  input_snapshot jsonb not null default '{}'::jsonb,
  result_snapshot jsonb not null default '{}'::jsonb,
  calculation_version text not null default 'loadiq-v1.1-profile-overhead',
  created_at timestamptz default now()
);

create table if not exists public.post_trip_actuals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  saved_load_id uuid not null references public.saved_loads(id) on delete cascade,
  actuals_snapshot jsonb not null default '{}'::jsonb,
  actual_net numeric(12,2),
  actual_fuel_price numeric(10,3),
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.lane_templates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  pickup_zip text not null,
  delivery_zip text not null,
  input_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.trip_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  saved_load_id uuid references public.saved_loads(id) on delete set null,
  status text not null default 'analyzed',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.calculation_overrides (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  saved_load_id uuid references public.saved_loads(id) on delete cascade,
  field_name text not null,
  original_profile_value numeric,
  override_value numeric,
  reason text,
  created_at timestamptz default now()
);

create table if not exists public.accessorial_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  saved_load_id uuid references public.saved_loads(id) on delete cascade,
  category text not null default 'misc',
  direction text not null default 'expense',
  amount numeric(12,2) not null default 0,
  is_reimbursed boolean not null default false,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
