import { calculateLoadMetrics } from "@/domains/calculator/calculator-engine";
import { DemoProfile, DemoSavedLoad } from "@/demo/loadiq-demo-types";
import { LoadInput } from "@/types/load";

export const demoProfile: DemoProfile = {
  operatorName: "Joshua Karpilo",
  companyName: "Karpilo Trucking LLC",
  truckYear: 2010,
  truckMake: "Peterbilt",
  truckModel: "387",
  equipmentType: "Flatbed",
  operatorType: "leased_owner_operator",
  carrierGrossPercent: 98,
  operatorPercent: 75,
  retainedBeforeSplitPercent: 2,
  dispatchFeePercent: 0,
  factoringFeePercent: 2.5,
  truckMpg: 6.7,
  averageFuelCost: 3.89,
  fuelReserve: 150,
  fixedOverheadDaily: 185,
  variableOverheadPerMile: 0.18,
  maintenanceReserve: 85,
  insurancePerLoad: 42,
  targetAnnualIncome: 95000,
  workingWeeks: 48,
  loadsPerWeek: 2.4,
  minimumTrueRpm: 2.15,
  minimumHourlyProfitability: 45,
};

export const demoFixedCosts = [
  ["Truck payment", "$3,150", "monthly"],
  ["Trailer payment", "$0", "monthly"],
  ["Physical damage insurance", "$1,050", "monthly"],
  ["Permits and registration", "$2,400", "annual"],
  ["ELD", "$45", "monthly"],
  ["Parking", "$180", "monthly"],
  ["Subscriptions", "$75", "monthly"],
  ["Phone and internet", "$145", "monthly"],
  ["Other fixed overhead", "$35", "weekly"],
] as const;

export const demoVariableCosts = [
  ["Maintenance reserve", "$0.12", "per mile"],
  ["Tires", "$0.06", "per mile"],
  ["Oil and PM reserve", "$35", "per load"],
  ["Dispatch percentage", "0%", "percentage"],
  ["Factoring percentage", "2.5%", "percentage"],
  ["Tolls", "Entered per trip", "flat"],
  ["Lumpers", "Entered per trip", "flat"],
  ["Washouts", "Entered per trip", "flat"],
  ["Permits", "Entered per trip", "flat"],
  ["Miscellaneous", "$25", "per load"],
] as const;

const profileDerivedValues = {
  dailyFixedOverhead: demoProfile.fixedOverheadDaily,
  operatingDaysPerWeek: 5.5,
  operatingDaysPerMonth: 23.8,
  dispatchPercent: demoProfile.dispatchFeePercent,
  factoringPercent: demoProfile.factoringFeePercent,
  maintenanceReserve: demoProfile.maintenanceReserve,
  tireReserve: 35,
  trailerFee: 0,
  insuranceAllocation: demoProfile.insurancePerLoad,
  variableCostPerMile: demoProfile.variableOverheadPerMile,
  fixedCostAllocation: 0,
  mpg: demoProfile.truckMpg,
  targetTrueRpm: demoProfile.minimumTrueRpm,
  incomeTargetDaily: demoProfile.targetAnnualIncome / 260,
  incomeTargetWeekly: demoProfile.targetAnnualIncome / 52,
  minimumHourlyProfitability: demoProfile.minimumHourlyProfitability,
};

export const demoLoadInput: LoadInput = {
  loadNumber: "DEMO-LIQ-1042",
  carrierLoadId: "MERCER-DEMO-771",
  dispatcherReference: "Demo dispatch board",
  pickupZip: "46241",
  pickupCity: "Indianapolis",
  pickupState: "IN",
  deliveryZip: "75261",
  deliveryCity: "Dallas",
  deliveryState: "TX",
  loadedMiles: 925,
  deadheadMiles: 82,
  routeLoadedMiles: 925,
  actualLoadedMiles: 0,
  routeDeadheadMiles: 82,
  actualDeadheadMiles: 0,
  dispatchDays: 2.5,
  deadheadDays: 0.25,
  loadRunStatus: "planned",
  ratePerMile: 2.7,
  fuelSurcharge: 345,
  fuelPrice: demoProfile.averageFuelCost,
  fuelPriceSource: "USER_OVERRIDE",
  fuelPriceSourceLabel: "Demo fuel price",
  fuelPriceRegion: "Midwest",
  fuelPricePeriod: "Demo Week",
  fuelPriceFetchedAt: "",
  fuelPriceExpiresAt: "",
  fuelPriceIsEstimate: true,
  mpg: demoProfile.truckMpg,
  overhead: demoProfile.fixedOverheadDaily,
  profileDerivedValues,
  temporaryOverrides: {},
  calculationSource: "profile",
  accessorialItems: [
    {
      id: "demo-accessorial-detention",
      category: "detention",
      amount: 120,
      direction: "revenue",
      isReimbursed: false,
      notes: "Demo detention revenue",
    },
    {
      id: "demo-accessorial-stop-pay",
      category: "extra_stop",
      amount: 75,
      direction: "revenue",
      isReimbursed: false,
      notes: "Extra stop pay",
    },
    {
      id: "demo-accessorial-lumper",
      category: "lumper",
      amount: 75,
      direction: "expense",
      isReimbursed: true,
      notes: "Demo reimbursed lumper",
    },
  ],
  reserveAllocation: demoProfile.fuelReserve,
  maintenanceReserve: demoProfile.maintenanceReserve,
  tireReserve: 35,
  tolls: 68,
  lumpers: 75,
  trailerFee: 0,
  insuranceAllocation: demoProfile.insurancePerLoad,
  variableCostPerMile: demoProfile.variableOverheadPerMile,
  fixedCostAllocation: 0,
  factoringPercent: demoProfile.factoringFeePercent,
  dispatchPercent: demoProfile.dispatchFeePercent,
  targetTrueRpm: demoProfile.minimumTrueRpm,
  payStructure: {
    type: "percentage",
    label: "75% of 98% gross",
    percentageChain: [98, 75],
    cpmRate: 0,
    flatAmount: 0,
    dailyRate: 0,
    includeFuelSurcharge: true,
    includeAccessorials: true,
  },
};

export const demoLoadResult = calculateLoadMetrics(demoLoadInput);

function createLoad(
  overrides: Partial<LoadInput>,
  id: string,
  name: string,
  status: DemoSavedLoad["status"],
  note: string,
  date: string
): DemoSavedLoad {
  const input: LoadInput = {
    ...demoLoadInput,
    ...overrides,
    profileDerivedValues: {
      ...demoLoadInput.profileDerivedValues,
      ...(overrides.profileDerivedValues ?? {}),
    },
  };

  return {
    id,
    name,
    status,
    ranLoad: status === "completed",
    date,
    input,
    result: calculateLoadMetrics(input),
    note,
  };
}

export const initialDemoSavedLoads: DemoSavedLoad[] = [
  createLoad(
    {
      loadNumber: "DEMO-LIQ-1038",
      carrierLoadId: "MERCER-DEMO-692",
      pickupZip: "63101",
      pickupCity: "St. Louis",
      pickupState: "MO",
      deliveryZip: "30337",
      deliveryCity: "Atlanta",
      deliveryState: "GA",
      loadedMiles: 555,
      deadheadMiles: 31,
      routeLoadedMiles: 555,
      routeDeadheadMiles: 31,
      dispatchDays: 1.5,
      deadheadDays: 0.1,
      ratePerMile: 2.85,
      fuelSurcharge: 210,
      tolls: 22,
      lumpers: 0,
      loadRunStatus: "ran",
    },
    "saved-demo-completed",
    "St. Louis to Atlanta",
    "completed",
    "Completed demo load with healthy true RPM and low deadhead exposure.",
    "May 9"
  ),
  createLoad(
    {},
    "saved-demo-potential",
    "Indianapolis to Dallas",
    "potential",
    "Potential load saved for comparison before accepting freight.",
    "May 10"
  ),
  createLoad(
    {
      loadNumber: "DEMO-LIQ-1040",
      pickupZip: "40219",
      pickupCity: "Louisville",
      pickupState: "KY",
      deliveryZip: "77032",
      deliveryCity: "Houston",
      deliveryState: "TX",
      loadedMiles: 940,
      deadheadMiles: 28,
      routeLoadedMiles: 940,
      routeDeadheadMiles: 28,
      dispatchDays: 2.6,
      ratePerMile: 2.95,
      fuelSurcharge: 310,
      tolls: 44,
      lumpers: 0,
      loadRunStatus: "planned",
    },
    "saved-demo-accepted",
    "Louisville to Houston",
    "accepted",
    "Accepted example because it clears the target even after overhead.",
    "May 11"
  ),
  createLoad(
    {
      loadNumber: "DEMO-LIQ-1041",
      pickupZip: "60638",
      pickupCity: "Chicago",
      pickupState: "IL",
      deliveryZip: "64153",
      deliveryCity: "Kansas City",
      deliveryState: "MO",
      loadedMiles: 515,
      deadheadMiles: 188,
      routeLoadedMiles: 515,
      routeDeadheadMiles: 188,
      dispatchDays: 1.8,
      deadheadDays: 0.35,
      ratePerMile: 2.35,
      fuelSurcharge: 130,
      tolls: 96,
      lumpers: 150,
      loadRunStatus: "test",
    },
    "saved-demo-rejected",
    "Chicago to Kansas City",
    "rejected",
    "Rejected demo load: too much deadhead and weak hourly return.",
    "May 12"
  ),
];

export const demoChecklistItems = [
  "Accept safety disclaimer",
  "Create operator profile",
  "Define pay structure",
  "Enter cost assumptions",
  "Set income target",
  "Calculate first load",
  "Save and review load",
] as const;
